- name: rabbitmq-component
  hosts: rabbitmq
  become: 'yes'
  tasks:
    - name: Configure YUM Repos
      ansible.builtin.yum:
        name: '{{item}}'
        state: installed
      loop:
        - >-
          curl -s
          https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
          | bash
        - >-
          curl -s
          https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh
          | bash
    - name: install rabbitmq-server
      ansible.builtin.yum:
        name: rabbitmq-server
        state: installed
    - name: start rabbitmq-server
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: 'yes'
    - name: default username
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123
    - name: password as guest
      ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
